name: CI - Karate POC

on:
  push:
    branches: [ "main" ]
  pull_request:
  workflow_dispatch:

env:
  ENV: dev

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 17
      uses: actions/setup-java@v4
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
  
    - name: Start Container
      run: |
        docker compose up -d --build

    - name: Tear down
      if: always()
      run: docker compose down -v
